/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/14/20, 9:32 PM' 
 * Generated by 'paulvan_mol1' 
 * Generated on server 'ODAWS02-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 Edg/86.0.622.38' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT%252B02%253A00&ticket=ST-297703-GPbWrsXl1OMHKqBazXzV-cas' 
 *
 */

/* Compute axis ranges */
proc means data=COVID.CASESBYDATE7DAVG noprint;
	class daten / order=data;
	var cases case7dayavg;
	output out=_BarLine_(where=(_type_ > 0)) sum(cases case7dayavg)=resp1 resp2;
run;

/* Compute response min and max values (include 0 in computations) */
data _null_;
	retain respmin 0 respmax 0;
	retain respmin1 0 respmax1 0 respmin2 0 respmax2 0;
	set _BarLine_ end=last;
	respmin1=min(respmin1, resp1);
	respmin2=min(respmin2, resp2);
	respmax1=max(respmax1, resp1);
	respmax2=max(respmax2, resp2);

	if last then
		do;
			call symputx ("respmin1", respmin1);
			call symputx ("respmax1", respmax1);
			call symputx ("respmin2", respmin2);
			call symputx ("respmax2", respmax2);
			call symputx ("respmin", min(respmin1, respmin2));
			call symputx ("respmax", max(respmax1, respmax2));
		end;
run;

/* Define a macro for offset */
%macro offset ();
	%if %sysevalf(&respmin eq 0) %then
		%do;
			offsetmin=0 %end;

	%if %sysevalf(&respmax eq 0) %then
		%do;
			offsetmax=0 %end;
%mend offset;

ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgplot data=COVID.CASESBYDATE7DAVG nocycleattrs;
	vbar daten / response=cases fillattrs=(color=CXdb5f2d) /*filltype=gradient*/ outlineattrs=(color=white)
		stat=sum;
	vline daten / response=case7dayavg lineattrs=(color=CXe90c05) stat=sum y2axis;
	xaxis type=time; 
	yaxis grid min=&respmin max=&respmax %offset();
	y2axis min=&respmin max=&respmax %offset();
	keylegend / location=outside;
	where daten between today()-120 and today();
run;

ods graphics / reset;

proc datasets library=WORK noprint;
	delete _BarLine_;
	run;